### ISSUE TITLE
 Cannot read property 'angleBetween' of undefined

### ISSUE THREAD

**Issue by ericzwong** [P5-wrapper/react#10]
I output the incoming function inside the p5, found no p5.Vector，can you fix it

**Comment by bsaphier** [comment]
can you provide an example of the code you are running?

**Comment by anselanza** [comment]
Yeah I also have a similar issue. Trying to use `p5.Vector.sub` (static method) but obviously `p5` is not defined but neither is `p.p5`.

**Comment by vennsoh** [comment]
Solution: 
https://github.com/and-who/react-p5-wrapper/issues/32

@anselanza @wangzhe1995
