### ISSUE TITLE
Auto-formatting doesn't work on push to master

### ISSUE THREAD

**Issue by yevdyko** [P5-wrapper/react#104]
@jamesrweb There is an error in CI when running git-auto-commit action:

```
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: At least 1 approving review is required by reviewers with write access.        
To https://github.com/jamesrweb/react-p5-wrapper
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/jamesrweb/react-p5-wrapper'
```

https://github.com/jamesrweb/react-p5-wrapper/runs/2925875088

**Comment by yevdyko** [comment]
@jamesrweb I guess the issue can be resolved by changing settings: [Cannot push on github suddently@stackoverflow](https://stackoverflow.com/a/60989585/6937763)

**Comment by jamesrweb** [comment]
Actually our setup is fine, GitHub must have changed something. [As outlined by the auto-commit-action docs](https://github.com/stefanzweifel/git-auto-commit-action#push-to-protected-branches) we include the personal access token and so there shouldn't be an issue, this happened just today and so I assume GitHub themselves updated something in the permissions panel. Will look into it more through the week.

**Comment by yevdyko** [comment]
It looks like `push_options: --force` helped 🎉

**Comment by jamesrweb** [comment]
As the pr branch name said though, it is just a patch to make it "work" because this causes two CI runs. One for the format commit and one after. This isn't resolved. Still needs investigated as I said.
