### ISSUE TITLE
can't play music

### ISSUE THREAD

**Issue by peter100u** [P5-wrapper/react#111]
sketch.js:15 Uncaught TypeError: p.loadSound is not a function
    at _.p.setup (sketch.js:15)
    at _setup (p5.min.js:3)
    at _start (p5.min.js:3)

**Comment by jamesrweb** [comment]
Without seeing your code or an example usage with a write up about what you are trying to achieve, I can't help you. Please always add context when raising issues. Perhaps #61 or #11 or #62 will be helpful but I don't know if that will be the case without you providing me with context.
