### ISSUE TITLE
Add typescript example to the readme

### ISSUE THREAD

**Issue by jamesrweb** [P5-wrapper/react#116]
Currently there are questions as to how the typescript integration works and so adding an example should clear that up for people interested in using typescript for their projects.

**Comment by jamesrweb** [comment]
Blocked by #117

**Comment by disambiguator** [comment]
Hi! I don't think the types are actually being exported correctly right now when you are publishing versions of the package - I think you need to add
```
"types": "dist/index.d.ts"
```
to your package.json.

See https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by jamesrweb** [comment]
> Hi! I don't think the types are actually being exported correctly right now when you are publishing versions of the package - I think you need to add
> 
> ```
> 
> "types": "dist/index.d.ts"
> 
> ```
> 
> to your package.json.
> 
> 
> 
> See https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

@disambiguator I will test this as part of the fix I am trying to find for #117, this might be the issue, will validate tomorrow 👌🏻

Thanks for the comment, super helpful even if it isn't the required fix 💯🌟

**Comment by jamesrweb** [comment]
This is currently blocked by #117. Until we resolve the `P5Instance` interface issue that currently exists, there isn't a reason to add TS documentation. Hoping to resolve #117 ASAP.
