### ISSUE TITLE
Issues with the `P5Instance` interface

### ISSUE THREAD

**Issue by jamesrweb** [P5-wrapper/react#117]
## Expected Behavior

All `p5` methods are exposed as part of the `P5Instance` interface.

## Actual Behavior

Inside the project [source code](https://github.com/jamesrweb/react-p5-wrapper/blob/master/src/index.tsx) everything works as expected, tests pass, etc.

During compilation however there seems to be some issue happening because when the project is utilised with typescript, the `P5Instance` interface doesn't seem to recognise the `p5` standard methods as it should since `P5Instance` extends `p5`.

I have a suspicion that this is because `p5` exposes a class, an interface and a namespace which all have the name `p5` and maybe this is causing the issue but I could be wrong about this assumption.

## Steps to Reproduce the Problem

This is the sketch I used to identify the issue:

```typescript
import React, { useState, useEffect } from "react";
import { P5Instance, ReactP5Wrapper } from "react-p5-wrapper";

function sketch(p5: P5Instance) {
  let rotation = 0;

  p5.setup = () => p5.createCanvas(600, 400, p5.WEBGL);

  p5.updateWithProps = props => {
    if (props.rotation) {
      rotation = (props.rotation * Math.PI) / 180;
    }
  };

  p5.draw = () => {
    p5.background(100);
    p5.normalMaterial();
    p5.noStroke();
    p5.push();
    p5.rotateY(rotation);
    p5.box(100);
    p5.pop();
  };
}

export default function App() {
  const [rotation, setRotation] = useState(0);

  useEffect(() => {
    const interval = setInterval(
      () => setRotation(rotation => rotation + 100),
      100
    );

    return () => {
      clearInterval(interval);
    };
  }, []);

  return <ReactP5Wrapper sketch={sketch} rotation={rotation} />;
}
```

As you can see `updateWithProps` is correctly identified but the other standard `p5` methods / constants don't seem to be recognised for some reason and show errors when compiled.

Also tested with the a sketch constant utilising the `Sketch` type but the same issue is apparent since the `p5` value is a `P5Instance` also in this case, usage of that can be seen below:

```ts
import React, { useState, useEffect } from "react";
import { ReactP5Wrapper, Sketch } from "react-p5-wrapper";

const sketch: Sketch = p5 => {
  let rotation = 0;

  p5.setup = () => p5.createCanvas(600, 400, p5.WEBGL);

  p5.updateWithProps = props => {
    if (props.rotation) {
      rotation = (props.rotation * Math.PI) / 180;
    }
  };

  p5.draw = () => {
    p5.background(100);
    p5.normalMaterial();
    p5.noStroke();
    p5.push();
    p5.rotateY(rotation);
    p5.box(100);
    p5.pop();
  };
}

export default function App() {
  const [rotation, setRotation] = useState(0);

  useEffect(() => {
    const interval = setInterval(
      () => setRotation(rotation => rotation + 100),
      100
    );

    return () => {
      clearInterval(interval);
    };
  }, []);

  return <ReactP5Wrapper sketch={sketch} rotation={rotation} />;
}
```

## Specifications

Package Version: >= 3.0.0

## Additional Comments

Perhaps it is my typescript config that is the issue, to double check the validity of this, can you try to reproduce locally also @yevdyko? If this is reproducible, I will look into this issue ASAP.

**Comment by jamesrweb** [comment]
@disambiguator & @yevdyko  version 3.0.1 has now been released with the package `types` hint added. I just tested if it fixed this issue or not and it seems it doesn't resolve the issue still. Any ideas come to mind on your end how to resolve this?

**Comment by disambiguator** [comment]
@jamesrweb your example works for me and I'm getting all type definitions working on >=4.0.0
<img width="904" alt="Screen Shot 2021-09-22 at 10 14 14 PM" src="https://user-images.githubusercontent.com/2306794/134445457-aa2c83b5-0643-48b9-a272-e4b3b7bc4284.png">
!

**Comment by disambiguator** [comment]
Interesting, I just used create-react-app to make a repro case and am running into this problem now as well.

**Comment by disambiguator** [comment]
a-ha! I found your problem. The types you have work properly, BUT you also need types for p5!
```
npm install --save-dev @types/p5
```
or
```
yarn add --dev @types/p5
```

**Comment by disambiguator** [comment]
I see that you actually have @types/p5 in your package.json already, so I'm not sure if there needs to be a way to surface it to people consuming the package as well.

One random thought - maybe `@types/p5` needs to be in `dependencies` and not just `devDependencies`?

**Comment by jamesrweb** [comment]
@disambiguator what if they are moved to the `peerDependencies`, that should also be fine, right?

**Comment by jamesrweb** [comment]
If that looks fine for you then I can change and deploy in the coming 12-24 hours a new patch version.

**Comment by jamesrweb** [comment]
@disambiguator @yevdyko I will be releasing the patch today alongside the TypeScript documentation changes required for #116 using the examples from this issue in the README 👌🏻!
