### ISSUE TITLE
does not work with isomorphic react apps

### ISSUE THREAD

**Issue by kkarkos** [P5-wrapper/react#2]
Unfortunately p5 won't work with isomorphic react apps due to `window` and `document`requirements. Any thoughts?

**Comment by bsaphier** [comment]
why would you want any p5 stuff to render server side?

**Comment by kkarkos** [comment]
No, I would not want to use it on the server of course. Problem is that with isomorphic/universal react apps the server will load the same JS as on the client, so the code is "isomorph". Some animation libraries use a shim or something like 

`if (typeof(window) == 'undefined'){` 

So on the server `window` would be skipped. I think this is more a feature and than an issue.

**Comment by bsaphier** [comment]
Oh, I see what you mean.
Wouldn't it work to just put that logic inside the function that you pass to the sketch prop?

**Comment by kkarkos** [comment]
Unfortunately not - once I call 'import X from Y' in a component and this component get's loaded on the server, library + dependencies will be loaded. In 'react-p5-wrapper' p5.js is a dependency which causes the error. So if I am correct p5.js would need to implement the 'if (window)' which would then also work for 'react-p5-wrapper'. That's what I think, but there might be other ways I am not aware of.

**Comment by bsaphier** [comment]
@kkarkos I wonder... would the new [dynamic imports](http://2ality.com/2017/01/import-operator.html) in ESNext fix this issue?

**Comment by jay-manday** [comment]
@bsaphier they do! the only big problem i've been trying to overcome is the issue of using things like `window.innerWidth` inside of the sketch for to make it responsive rather than with explicit x, y values

**Comment by jmandel1027** [comment]
This is still a big issue and causing me a lot of trouble. I tried dynamic importing and it almost worked, the browser rendered the canvas for a second and then crashed. Definitely would love to see this happen!

**Comment by hifilorau** [comment]
@jay-manday @kkarkos Did you guys ever figure out a solution to this issue? It's killing me.

**Comment by justinsunho** [comment]
Was facing this issue when trying to use `react-p5-wrapper` in [gatsby](https://www.gatsbyjs.org/).
Just moved the `p5` import into `componentDidMount()`. It's been working for me.

If anyone else has a better solution, I'm all ears.

**Comment by hifilorau** [comment]
@justinsunho are you saying you pulled p5 itself out as a dependency of the wrapper and then imported p5 via either CDN or from a .js file in componentDidMount()? I've been building a lot of gatsby sites in the last year and have been trying to get p5 working on and off throughout that time. I feel like i tried something like that once and failed, but if you got it to work and build in gatsby or netlify i want back in!!! Thanks

**Comment by justinsunho** [comment]
@hifilorau  I did eventually get it working. Although to be completely honest, I've been using gatsby to learn react so I'm not super sure if it's hacky or not. 

I ended up not using this wrapper and instead writing my own: https://github.com/justinsunho/website/tree/master/src/components

I imported `p5` from npm on my own.

Check out `p5component.js` and `sketchData.js`. I also am dynamically rendering the sketches in gatsby if you wanted to check that out too. 

I mainly based a lot of my work on @jinksi's `create-react-app` site: https://github.com/Jinksi/jinksi-react (viewable at https://v2.ericjinks.com).

You can see my stuff in action at justinsunho.com, but keep in mind that it's all still in flux.

Also, if you have any tips, I'm more than glad to hear them! Super new to react and gatsby and p5 have been such fun ways of learning about it.

**Comment by trafnar** [comment]
This seems to be working for me (using recommendations from [this gatsby documentation page](https://www.gatsbyjs.org/docs/using-client-side-only-packages/))

The code below is Typescript, you'll need to alter it slightly if you are using regular JS.

Create a new custom component which uses [Loadable](https://www.smooth-code.com/open-source/loadable-components/)

```typescript
import Loadable from "@loadable/component"
export const loadableP5 = Loadable(() => import('react-p5-wrapper'))
```

instead of importing P5Wrapper, import that custom component, then use it as usual.
```typescript
import {loadableP5 as P5Wrapper} from './loadableP5'
```

**Comment by jamesrweb** [comment]
Closing due to the solutions outlined above being viable.

You can alternatively include the wrapper directly into your HTML output file using [this UNPKG link](https://unpkg.com/react-p5-wrapper) and then use P5 as usual in the wrapper.

**Comment by graeme120** [comment]
> Hey. having trouble with this same issues many years later. I don't think your website repo link is working anymore. Do you have any other examples of using gatsby and p5 together that get the job done? Would help me out so much

**Comment by graeme120** [comment]
> @hifilorau I did eventually get it working. Although to be completely honest, I've been using gatsby to learn react so I'm not super sure if it's hacky or not.
> 
> I ended up not using this wrapper and instead writing my own: https://github.com/justinsunho/website/tree/master/src/components
> 
> I imported `p5` from npm on my own.
> 
> Check out `p5component.js` and `sketchData.js`. I also am dynamically rendering the sketches in gatsby if you wanted to check that out too.
> 
> I mainly based a lot of my work on @Jinksi's `create-react-app` site: https://github.com/Jinksi/jinksi-react (viewable at https://v2.ericjinks.com).
> 
> You can see my stuff in action at justinsunho.com, but keep in mind that it's all still in flux.
> 
> Also, if you have any tips, I'm more than glad to hear them! Super new to react and gatsby and p5 have been such fun ways of learning about it.

@justinsunho Hey. having trouble with this same issues many years later. I don't think your website repo link is working anymore. Do you have any other examples of using gatsby and p5 together that get the job done? Would help me out so much

**Comment by Allakazan** [comment]
The solution isn't viable anymore. Won't work on Remix
