### ISSUE TITLE
Passing props to sketch function

### ISSUE THREAD

**Issue by F-Moody** [P5-wrapper/react#21]
Hello there,
i have a sketch function ( same as the one on the first example) and i want to pass some props to this function and i cant understand how.
So i have the index.js file which is something like this 

`import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import P5Wrapper from 'react-p5-wrapper';
import sketch from './demo';

class App extends Component {
    state = {
        x: undefined,
        y: undefined
    }

    onMove(e){
        this.setState({x:e.screenX, y: e.screenY})
    }

     
    render() {
    return (
      <div className="App" onMouseMove={(e) => this.onMove(e)}>
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
            <P5Wrapper sketch={sketch} />
        </p>
      </div>
    );
  }

}

export default App;`

and my sketch function is this

`
export default function sketch (p) {
    let rotation = 0;

    p.setup = function () {
        p.createCanvas(800, 800, p.WEBGL);
        p.angleMode('DEGREES');
    };

    p.myCustomRedrawAccordingToNewPropsHandler = function (props) {
        if (props.rotation){
            rotation = props.rotation * Math.PI / 180;
        }
    };

    p.draw = function () {
        p.background(100);
        p.stroke(255);
        p.push();
        p.rotateX(rotation);
       // p.box(100);
        p.fill(255);
       // p.rotate(10);
        p.translate(props.x,props.y);
        p.rect(0,0,100,50);
        p.pop();
    };
};`

now as you can see i want to pass down x and y to my sketch, but i can't figure out how

**Comment by rhysstubbs** [comment]
I am also having issues passing props to my component, I am using the example source code provide but props remain undefined?

**Comment by and-who** [comment]
`props` is an Argument of the `myCustomRedrawAccordingToNewPropsHandler` Function.
So props is not in the Scope of the `draw` Function
