### ISSUE TITLE
Capture webcam video with createCapture() but not found 

### ISSUE THREAD

**Issue by oukunan** [P5-wrapper/react#22]
I tried to capture video with my webcam but react-p5-wrapper not found function createCaptrue(). Or I miss something?

**Comment by toroduque** [comment]
Try importing the `p5.dom.js` library.  This worked for me:

```
import "react-p5-wrapper/node_modules/p5/lib/addons/p5.dom";

export default function sketch(p5) {

  p5.setup = function() {
        // Create a video element
        video = p5.createCapture(p5.VIDEO);
   }
```

**Comment by futurouz** [comment]
@toroduque  My p5 variable got undefined. What should I do ?

**Comment by oukunan** [comment]
@toroduque  that's work!. thanks.

**Comment by rickithadi** [comment]
getting a module not found error for p5.dom .Checking node_modules also shows that the file isnt there. Could you post a gist or a link to your repo please

**Comment by and-who** [comment]
p5 is now a peerDependency, so it should be in your node_modules Folder.
So you should do something like `import "p5/lib/addons/p5.dom";`

**Comment by rickithadi** [comment]
wow that works. Worth noting that the import is not in the sketch.js file but the component. thanks
