### ISSUE TITLE
bundle size over 1mb

### ISSUE THREAD

**Issue by ngmiduc** [P5-wrapper/react#26]
Hi,
I just imported the react-p5-wrapper into my website and suddenly the bundle increases by 1mb. Is that normal? It can not be that this bundle is that huge after production.

Version: webpack 4.27.1

**Comment by subodhpareek18** [comment]
Linked to this I think, not an issue with the wrapper.
https://github.com/processing/p5.js/issues/1734#issuecomment-390380630

**Comment by ngmiduc** [comment]
Yes I see
-close
