### ISSUE TITLE
react-p5-wrapper and minified p5.js

### ISSUE THREAD

**Issue by dhowe** [P5-wrapper/react#28]
Question: does the react-p5-wrapper use the minified version of p5.js (p5.min.js) ?
And if not, is there a way to force it to ?

**Comment by and-who** [comment]
Hi, I made p5 a peerDependency.
So you should be able to choose what Version of p5 you are using.

p5 ships with a minified Version but I'm not sure if e.g. webpack chooses this file over the "normal" File.
