### ISSUE TITLE
Any plans to implement react hooks?

### ISSUE THREAD

**Issue by vennsoh** [P5-wrapper/react#31]
Are there any future plans to refactor the code to use hooks and all the latest React goodness? I found one here which looks very promising but it's way to complex for a novice like me. https://discourse.processing.org/t/using-react-with-p5-js-es6-support/

**Comment by and-who** [comment]
I wouldn't add it just because.
If somebody comes up with a good reason, perhaps :)

**Comment by vennsoh** [comment]
I'm not super familiar with all things react but I heard react-p5-wrapper uses componentWillReceiveProps(). Since React 16.3 it has been replaced by UNSAFE_componentWillReceiveProps()? This lifecycle method is deprecated and will be removed from the next major release of React?

**Comment by and-who** [comment]
@vennsoh ohhh I didn't think of that, Thx!
I just build a Version 2.0.0 where it uses the `getDerivedStateFromProps(props, state)`-Function instead. ([npm Repo](https://www.npmjs.com/package/react-p5-wrapper))
I didn't tested it very well. But from the first glance it should work.

**Comment by Maybach91** [comment]
Thanks @and-who, how to use this? The same like in the mentioned processing reference? 
`<P5Wrapper sketch={sketch} foo="bar" />` does not work for me. i need to access `foo` within my `sketch` module. :/
