### ISSUE TITLE
How to use p5.Vector.random2D() static method?

### ISSUE THREAD

**Issue by vennsoh** [P5-wrapper/react#32]
If I'm trying to use static method like p5.Vector.random2D() https://p5js.org/reference/#/p5.Vector/random2D

How can I use it?
`
import p5 from "p5"
export default function sketch(p) {
    p.setup = () => {
    }
    p.draw = () => {
        p.background(240)
        let v1 = p5.Vector.random2D()
    }
}
`

**Comment by vennsoh** [comment]
I think I manage to figure this out :)
You can either:
`import * as p5 from "p5";`
instead of 
`import p5 from "p5"`

because {Vector} is a named export.
Or you can just do
`import {Vector} from "p5"`

Then you can use it `p5.Vector.random()`

**Comment by jonxuxu** [comment]
Works for me! Just do:

```
import {Vector} from "p5";

const v = Vector.random();
```

**Comment by jonxuxu** [comment]
Actually realized that some vector functions completely break since the p5 object isn't the same as the global p5. Issue solved here: https://github.com/P5-wrapper/react/issues/42#issuecomment-633108409

**Comment by jamesrweb** [comment]
Thanks for keeping the thread up to date to help others in the future @JonathanXu1!
