### ISSUE TITLE
Unmet peer dependency.

### ISSUE THREAD

**Issue by derekkinsman** [P5-wrapper/react#4]
I get this warning when installing into React `v15.4.2`:

```
├── UNMET PEER DEPENDENCY react@15.4.2
└── react-p5-wrapper@0.0.3

npm WARN react-p5-wrapper@0.0.3 requires a peer of react@^0.14.0 but none was installed.
```

My `package.json` looks like this:

```
{
  /* stuff */

  "dependencies": {
    "react": "15.4.2",
    /* everything else */
  }
}

**Comment by hannahbeale** [comment]
@derekkinsman did you find a fix?

**Comment by bsaphier** [comment]
the PR i just opened should fix this issue but it should also be safe to ignore this warning in the meantime

**Comment by bsaphier** [comment]
I closed the issue because the fix is merged, but the npm package still needs to updated by @NeroCor
