### ISSUE TITLE
Navigating away from a route that uses react-p5-wrapper is crashing my app

### ISSUE THREAD

**Issue by johngribbin** [P5-wrapper/react#46]
Hey!

I am using `react-p5-wrapper` in a web app called TruSat, thank you for building it!

https://trusat.org/catalog/priorities 

The little badges in the table rows are rendered with help of your wrapper. The number of the sat is used to conditionally render a different colored badge for each.

I just found a weird bug whereby the app crashes (sometimes) when I click on a users name in the table to navigate to their profile page. 

When on the link I shared above, try clicking on the user named `SolarLyra` in the table (last column on right) and you will see that their profile page doesn't load - but it does when you refresh the page. If you can't replicate the bug, try repeating this process a couple of times by going back to the catalog page and click the username again in the table. 

When I check the console, I see the following error:

```
TypeError: Cannot read property 'remove' of null
    at t.componentWillUnmount
```

And upon further inspection, it originates to here- 

```
  P5Wrapper.prototype.componentWillUnmount = function () {
    this.state.canvas.remove();
  };
``` 

Any ideas what I can do on my end to help fix this bug? 

Thanks so much in advance!
John.

**Comment by julvo** [comment]
Getting the same error. Seems to happen when navigating away before `state.canvas` is initialised. Happy to submit a PR, a simple not-null check in `componentWillUnmount` should do the job.

**Comment by jamesrweb** [comment]
@julvo, @johngribbin I just added a fix for this in my PR #48 😄

**Comment by johngribbin** [comment]
Cheers @jamesrweb !!

**Comment by jamesrweb** [comment]
All good @johngribbin, hopefully this can be merged by @and-who soon-ish 🙂

**Comment by jamesrweb** [comment]
@johngribbin my PR resolving this issue was merged into the main repository and thus, the issue should now be resolved. I will close this issue for now but if the issue persists, please comment back here or open a new issue and I will apply any necessary hotfixes ASAP.
