### ISSUE TITLE
[Question] Is it possible to create an interactive robotic arm control?

### ISSUE THREAD

**Issue by Weffe** [P5-wrapper/react#5]
Hello,

I'm part of my robotics club at my university and am tasked with finding a way to provide a way to control our robotic arm. I've been looking at other JS libraries like EaselJS and Paper.js, etc. But I wanted to know if it would be possible to mimic the interactivity with P5.js & React.js as seen in this gif: http://www.alistairwick.com/assets/images/robot/ik.gif

 ([blog post the gif is from](http://robohub.org/robotics-maths-python-a-fledgling-computer-scientists-guide-to-inverse-kinematics/))

Anyways, I just need to be able to create an interactive way to provide 1 to 1 arm control for now. And if I figure things out for inverse kinematics than the setup of the controls should be pretty similar. We can assume the robotic arm I'm working on is a 3 degree of freedom arm as seen in the gif. 

Thanks so much!

**Comment by bsaphier** [comment]
That looks totally possible to make with P5. If you just want to make that animation, you don't need React for anything.

**Comment by Weffe** [comment]
Thanks for responding! I'm using React for the UI we have now so I want to keep it inside React. I've found another repo which looks promising and will try it out first: https://github.com/lavrton/react-konva

If that doesn't work out than I'll definitely consider p5.js. If you're curious this our repo we have for the Rover: https://github.com/CSUFTitanRover/TitanRover

Again, thanks for responding :) :+1:
