### ISSUE TITLE
I can't use React hooks inside of the Sketch file?

### ISSUE THREAD

**Issue by vennsoh** [P5-wrapper/react#58]
When I try to run React hooks, I get a bunch of errors:

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

I'm trying to use React hooks within here:

```
export default function sketch(p5) { 
...
}
```

**Comment by jamesrweb** [comment]
A sketch isn't a react component so this won't work.

You could do like [the example here](https://github.com/P5-wrapper/react/blob/master/example/app.jsx) which uses an input to update a rotation hook value which is then passed [to the sketch defined here](https://github.com/P5-wrapper/react/blob/master/example/sketches/box.js). Wouldn't this be the solution you're looking for?

**Comment by vennsoh** [comment]
Thanks @jamesrweb Yes! I've figured this out after understanding a bit more how React lift the states up https://reactjs.org/docs/lifting-state-up.html 

And` p5.myCustomRedrawAccordingToNewPropsHandler` is awesome!

Can close this now (:

**Comment by pony0pn** [comment]
> A sketch isn't a react component so this won't work.
> 
> You could do like [the example here](https://github.com/and-who/react-p5-wrapper/blob/master/example/src/app.jsx) which uses an input to update a rotation hook value which is then passed [to the sketch defined here](https://github.com/and-who/react-p5-wrapper/blob/master/example/src/sketches/sketch.js). Wouldn't this be the solution you're looking for?

Unfortunately those links are no longer live, could you share them another way?

I also saw you respond in another issue that you wouldn't implement hooks without a good reason, how about this, making async web3 calls and general web3-react integration within Processing. Currently working on a project that needs this, I think it will become increasingly useful as well!

Thanks so much

EDIT:
Ok I found the new path to the examples you linked and was able to pass in a function from the parent component that calls the hook and that worked!

**Comment by yevdyko** [comment]
The actual link for examples is [here](https://github.com/P5-wrapper/react/tree/master/example)

**Comment by jamesrweb** [comment]
Updated the links for future references to be in tact. 👍🏻
