### ISSUE TITLE
How to load plugins with this?

### ISSUE THREAD

**Issue by rchrd2** [P5-wrapper/react#62]
Is there a way to load p5 plugins using this wrapper?

**Comment by vennsoh** [comment]
Yes! I just asked a similar question the other day. If you look at the closed issues that mention how to load p5.sound you will see the solution

**Comment by jamesrweb** [comment]
@rchrd2 see [this comment](https://github.com/and-who/react-p5-wrapper/issues/61#issuecomment-730632590) which is what @vennsoh is referring to.

If that doesn't help, please just reply with a more specific example and question. Hope it helps though!

**Comment by rchrd2** [comment]
Thanks. It would be nice to have an example of including a plugin in the documentation.

At the time, I ended up not using this plugin and doing the following:

```
export default () => {
  let targetRef = React.createRef();
  React.useEffect(() => {
    new p5(sketch2, targetRef.current);
  }, []);
  return (
    <>
      <Head>
        <script src="/p5/p5.js"></script>
        <script src="/p5-play/lib/p5.play.js"></script>
        <script src="/p5/addons/p5.sound.min.js"></script>
      </Head>
      <div ref={targetRef}></div>
    </>
  );
};
```

Thanks for the suggestions.

**Comment by vennsoh** [comment]
> Thanks. It would be nice to have an example of including a plugin in the documentation.
> 
> At the time, I ended up not using this plugin and doing the following:
> 
> ```
> export default () => {
>   let targetRef = React.createRef();
>   React.useEffect(() => {
>     new p5(sketch2, targetRef.current);
>   }, []);
>   return (
>     <>
>       <Head>
>         <script src="/p5/p5.js"></script>
>         <script src="/p5-play/lib/p5.play.js"></script>
>         <script src="/p5/addons/p5.sound.min.js"></script>
>       </Head>
>       <div ref={targetRef}></div>
>     </>
>   );
> };
> ```
> 
> Thanks for the suggestions.

Interesting approach! Do you happen to have a repo to demonstrate how you put all these together? I'd love to learn. Thanks.

**Comment by rchrd2** [comment]
Unfortunately this is not for a public repository. I forgot to mention I was using nextjs. So `<Head>` comes from `next-head`.
