### ISSUE TITLE
How do you incorporate a p5 Sketch file with additional .js files

### ISSUE THREAD

**Issue by vennsoh** [P5-wrapper/react#66]
There are a few p5 tutorials out there that have additional .js files they use to import in for the p5 experience.
I'm trying to follow this tutorial here: https://thecodingtrain.com/CodingChallenges/115-snake-game-redux.html

Re-creating the exact same thing in React by copy-pasting the code.
But to get it to work with React-p5-wrapper and React in general seems hard?

Here is my demo code.
https://codesandbox.io/s/immutable-wave-z20tv?file=/src/App.js

**UPDATE:** I think I manage to fix it but I'm getting a ton of console errors which I don't quite understand.

**Comment by jamesrweb** [comment]
Hey @vennsoh I checked your REPL but there doesn't seem to be errors there, did you resolve the issue in the end?

**Comment by vennsoh** [comment]
Ah yes! I've managed to fix it! Thanks.

**Comment by jamesrweb** [comment]
No problem @vennsoh, thanks for closing and letting me know! 😄
