### ISSUE TITLE
Type signatures for TypeScript projects

### ISSUE THREAD

**Issue by disambiguator** [P5-wrapper/react#72]
Any thoughts on publishing type signatures for this project? I've worked around this locally by doing...

`lib/types.ts`
```
import * as p5 from 'p5';
import { ComponentType } from 'react';

export type P5WrapperComponent = ComponentType<{ sketch: (p: p5) => void }>;
```

`index.d.ts`
```
declare module 'react-p5-wrapper' {
  import { P5WrapperComponent } from './lib/types';
  export default P5WrapperComponent;
}
```

**Comment by jamesrweb** [comment]
This will be done in the future when #65 is implemented but this will take some time as the process for v3 has just began.

Closing issue for now since to implement this today isn't as easy as you'd think with the current setup but will be in v3 as I said.
