### ISSUE TITLE
importing p5.dom.js in React

### ISSUE THREAD

**Issue by johnneuland** [P5-wrapper/react#74]
```
  p5.setup = function() {
    video = p5.createCapture(p5.VIDEO);}
```
To use this code, I need to import an addon. I tried both ways of importing:
```
import "react-p5-wrapper/node_modules/p5/lib/addons/p5.dom";
import "p5/lib/addons/p5.dom";
```
but I get an error that:
```
Can't resolve 'p5/lib/addons/p5.dom' in '/home/new/src/pages/myPage'
```
My package.json file has this:
```
    "react-dom": "^17.0.1",
    "react-p5": "^1.3.6",
    "react-p5-wrapper": "^2.3.0",
```

**Comment by jamesrweb** [comment]
Please follow the guidance in [my comment](https://github.com/and-who/react-p5-wrapper/issues/61#issuecomment-730632590) on #61. I would also advise updating to the latet version I just released (2.4.0) which resolves #39.
