### ISSUE TITLE
Type annotations

### ISSUE THREAD

**Issue by kyeshmz** [P5-wrapper/react#78]
Hi, just wanted to say that this has helped me so much!
I was wondering how you thought about type annotations with this project, more specifically with things like myCustomRedrawAccordingToNewPropsHandler as it shows as an error in typescript projects.

I am  currently just using this fix in my project
```
import * as p5 from 'p5';

export type ReactP5 = p5 & {
  myCustomRedrawAccordingToNewPropsHandler: (props: any) => void;
};
```
but would you want to just make still p5 or change the name for typing reasons

**Comment by jamesrweb** [comment]
Hi @kyeshmz, I am currently planning a refactor which will include new typings among other things, so keep your eye out for that, it will come sooner than later 😄!
