### ISSUE TITLE
Changing state causes the a new wrapper to created

### ISSUE THREAD

**Issue by TheWuster935** [P5-wrapper/react#83]
Hi all, 
I am not sure if this is expected behavior but whenever I change the state outside of the component it causes a new wrapper to be created and added to the DOM below.  I have attached a codesandbox below.

https://codesandbox.io/s/blissful-sun-gfz10?file=/src/App.js

**Comment by jamesrweb** [comment]
When you change the state you recreate the `sketch` function and since this is a new sketch as far as react is concerned, it is re-rendered but the old one cannot be cleaned up since react still has a reference to the old instance internally.

To make it work you need to extract the `sketch` function like so:

```jsx
import "./styles.css";
import React from "react";
import P5Wrapper from "react-p5-wrapper";

let a = 300;
let b = 300;
let speed = 3;

const sketch = (p5) => {
  p5.setup = () => p5.createCanvas(600, 500);

  p5.myCustomRedrawAccordingToNewPropsHandler = (props) => {};

  p5.draw = () => {
    p5.background("rgb(100%,0%,100%)");
    p5.stroke(255);
    p5.strokeWeight(4);
    p5.noFill();
    p5.rect(a, b, 100, 200);
    if (a >= p5.width) {
      speed = -3;
    }
    if (a === 90) {
      speed = 3;
    }
    a = a + speed;
  };
};

export default function App() {
  const [test, setTest] = React.useState(false);

  return (
    <>
      <div className="App">
        <button onClick={() => setTest((test) => !test)}>
          {"test: " + test}
        </button>
      </div>
      <P5Wrapper sketch={sketch} test={test} />
    </>
  );
}
```
