### ISSUE TITLE
Investigate how to run CI on PRs to master and on merges to master (also for forks)

### ISSUE THREAD

**Issue by jamesrweb** [P5-wrapper/react#89]

**Comment by yevdyko** [comment]
I don't think it's worth the effort for such a small project. If it seems relevant to you, you can keep the issue open.

**Comment by jamesrweb** [comment]
It's to resolve the issue you had when trying to make a PR from your fork of the project, remember?

**Comment by yevdyko** [comment]
Yeah, I know, but it's a minor thing, so I don't want to invest my time in it as I'm happy with the current setup.

**Comment by jamesrweb** [comment]
Closing as the issue seems to be resolved after testing.
