### ISSUE TITLE
Will future versions of react be added to the project ?

### ISSUE THREAD

**Issue by dolphin007x** [P5-wrapper/react#92]
Hi, just found this repository !! By the way, will future versions of react be added to this project ? 

### If anyone knows anything about this, please do respond ASAP !!

**Comment by jamesrweb** [comment]
Going forward we aim to support the last 2 major versions of react so every new version will be supported as required 🙂. Does this answer your question sufficiently?

**Comment by dolphin007x** [comment]
Yes it does! Thanks !
