### ISSUE TITLE
Use parcel instead of webpack to build the example

### ISSUE THREAD

**Issue by yevdyko** [P5-wrapper/react#95]
I think we could try using `parcel` to build the example instead of `webpack` to avoid configurations and reduce dependencies. As we have a very small example application, `parcel` might be a suitable solution.

Relevant link: https://v2.parceljs.org/

**Comment by jamesrweb** [comment]
We could also use `rollup` like we do in the version 3 branch, perhaps a discussion topic for our next meeting?

**Comment by yevdyko** [comment]
@jamesrweb Since you are going to use `rollup`, this idea is no longer relevant. Closing the issue.
