### ISSUE TITLE
Enable Dependabot security updates

### ISSUE THREAD

**Issue by yevdyko** [P5-wrapper/react#97]
@jamesrweb What do you think about enabling Dependabot to easily update vulnerable dependencies?

**Comment by jamesrweb** [comment]
@yevdyko it should already be on actually, I will check the settings later to be sure though!

**Comment by jamesrweb** [comment]
Dependabot is on in the settings as I thought. Did you notice an issue that made you think this wasn't the case?

<img width="939" alt="Bildschirmfoto 2021-06-21 um 10 10 38" src="https://user-images.githubusercontent.com/47126579/122728957-f0a22a00-d278-11eb-9e0e-cf23c5ca85a6.png">

**Comment by yevdyko** [comment]
Hmm, let's see if dependabot creates a PR with a dependency update to fix the vulnerability next time.
